import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Content-Type': 'application/json' }
const reply = (body: Record<string, unknown>, status = 200) => new Response(JSON.stringify(body), { status, headers: cors })
const iso = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const plusDays = (date: string, days: number) => { const [y,m,d] = date.split('-').map(Number); return iso(new Date(y,m-1,d+days)) }
const day = (date: string) => { const [y,m,d] = date.split('-').map(Number); return new Date(y,m-1,d).getDay() }
const overlaps = (a: string,b: string,c: string,d: string) => a < d && c < b

Deno.serve(async request => {
  if (request.method === 'OPTIONS') return new Response('ok', { headers: cors })
  if (request.method !== 'POST') return reply({ error: 'Method not allowed.' }, 405)
  const token = request.headers.get('Authorization')?.replace(/^Bearer\s+/i, '')
  if (!token) return reply({ error: 'Sign in to use the Revision Planner.' }, 401)
  const url = Deno.env.get('SUPABASE_URL') ?? '', serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
  const auth = createClient(url, Deno.env.get('SUPABASE_ANON_KEY') ?? '', { global: { headers: { Authorization: `Bearer ${token}` } }, auth: { persistSession: false } })
  const admin = createClient(url, serviceKey, { auth: { persistSession: false } })
  let requestId: string | null = null
  try {
    const { data: { user }, error: authError } = await auth.auth.getUser()
    if (authError || !user) return reply({ error: 'Your session is no longer valid.' }, 401)
    const body = await request.json(), mode = body?.mode, planId = typeof body?.plan_id === 'string' ? body.plan_id : ''
    const instruction = typeof body?.instruction === 'string' ? body.instruction.trim() : ''
    if (!planId || !['generate','edit','apply_edit'].includes(mode) || (mode === 'edit' && !instruction) || (mode === 'apply_edit' && !Array.isArray(body?.changes))) return reply({ error: 'Invalid planner request.' }, 400)
    const [{ data: permission }, { data: plan, error: planError }] = await Promise.all([
      admin.from('user_workspace_permissions').select('workspace').eq('user_id', user.id).eq('workspace', 'academics').maybeSingle(),
      admin.from('academic_revision_plans').select('*').eq('id', planId).eq('owner_id', user.id).maybeSingle(),
    ])
    if (!permission || !plan || planError) return reply({ error: 'This Revision Plan is unavailable.' }, 403)
    const { data: requestRow } = mode === 'apply_edit' ? { data: body.request_id ? { id: body.request_id } : null } : await admin.from('academic_revision_ai_requests').insert({ owner_id:user.id, plan_id:planId, request_type:mode, status:'pending' }).select('id').single()
    requestId = requestRow?.id ?? null
    const tables = await Promise.all(['academic_revision_exams','academic_revision_commitments','academic_revision_topics','academic_revision_topic_activities','academic_revision_sessions','academic_subjects','academic_topics','academic_comments'].map(table => admin.from(table).select('*').eq('owner_id',user.id)))
    if (tables.some(result => result.error)) throw new Error('Planner data could not be loaded.')
    const [exams, commitments, revisionTopics, activities, sessions, subjects, topics, comments] = tables.map(result => result.data || [])
    const planExams = exams.filter((x:any)=>x.plan_id===planId), planTopics = revisionTopics.filter((x:any)=>x.plan_id===planId), planSessions = sessions.filter((x:any)=>x.plan_id===planId)
    const topicIds = new Set(planTopics.map((x:any)=>x.topic_id).filter(Boolean)), activityByTopic = new Map<string, any[]>()
    activities.forEach((x:any)=>{ const list=activityByTopic.get(x.revision_topic_id)||[]; list.push(x); activityByTopic.set(x.revision_topic_id,list) })
    if(mode === 'apply_edit') {
      const changes = body.changes as any[], sessionById = new Map(planSessions.map((x:any)=>[x.id,x])), knownExams = new Set(planExams.map((x:any)=>x.id)), topicById = new Map(planTopics.map((x:any)=>[x.id,x])), subjectIds = new Set(subjects.map((x:any)=>x.id))
      if (!changes.length || changes.some(change=>!['move','create','remove','resize'].includes(change?.action))) throw new Error('Invalid AI adjustment.')
      const occupied = planSessions.map((session:any)=>({...session})), proposedIds = new Set<string>()
      const validateTiming = (item:any, exclude?:string) => { const topic=topicById.get(item.revision_topic_id); if(!knownExams.has(item.exam_id)||!topic||!subjectIds.has(item.subject_id)||topic.subject_id!==item.subject_id||(topic.topic_id||null)!==(item.topic_id||null)||!activityByTopic.get(topic.id)?.some((a:any)=>a.activity_label===item.activity_label)) throw new Error('Your timetable changed after this preview was created. Generate a fresh adjustment and try again.'); if(item.scheduled_date<plan.start_date||item.scheduled_date>plan.end_date||item.scheduled_date>planExams.find((e:any)=>e.id===item.exam_id)?.exam_date||!item.start_time||!item.end_time||item.start_time>=item.end_time) throw new Error('Your timetable changed after this preview was created. Generate a fresh adjustment and try again.'); const weekend=[0,6].includes(day(item.scheduled_date)),wake=weekend?plan.weekend_wake_time:plan.weekday_wake_time,sleep=weekend?plan.weekend_sleep_time:plan.weekday_sleep_time;if((wake&&item.start_time<wake)||(sleep&&item.end_time>sleep))throw new Error('Your timetable changed after this preview was created. Generate a fresh adjustment and try again.'); const blocked=[...occupied.filter((x:any)=>x.id!==exclude),...commitments.filter((x:any)=>x.plan_id===planId&&((x.recurrence_type==='once'&&x.specific_date===item.scheduled_date)||(x.recurrence_type==='weekly'&&Number(x.day_of_week)===day(item.scheduled_date)))];if(blocked.some((x:any)=>overlaps(item.start_time,item.end_time,x.start_time,x.end_time)))throw new Error('Your timetable changed after this preview was created. Generate a fresh adjustment and try again.'); }
      for(const change of changes){if(change.action==='create'){validateTiming(change);occupied.push({...change,id:'new-'+occupied.length});continue}const session=sessionById.get(change.session_id);if(!session||session.locked||session.status==='done'||proposedIds.has(session.id))throw new Error('Your timetable changed after this preview was created. Generate a fresh adjustment and try again.');proposedIds.add(session.id);if(change.action==='remove'){const index=occupied.findIndex((x:any)=>x.id===session.id);if(index>=0)occupied.splice(index,1);continue}validateTiming({...session,...change},session.id);Object.assign(occupied.find((x:any)=>x.id===session.id),change)}
      const { error: applyError } = await admin.rpc('apply_revision_ai_changes',{p_plan_id:planId,p_owner_id:user.id,p_changes:changes})
      if(applyError) throw applyError
      if(requestId) await admin.from('academic_revision_ai_requests').update({status:'applied',applied_at:new Date().toISOString()}).eq('id',requestId).eq('owner_id',user.id)
      const summary={moved:changes.filter(c=>c.action==='move'||c.action==='resize').length,created:changes.filter(c=>c.action==='create').length,removed:changes.filter(c=>c.action==='remove').length}
      return reply({applied:true,summary})
    }
    const input = { plan: Object.fromEntries(['start_date','end_date','weekday_wake_time','weekday_sleep_time','weekend_wake_time','weekend_sleep_time','weekday_homework_reserve_minutes','weekend_homework_reserve_minutes','minimum_session_minutes','maximum_session_minutes','break_minutes','maximum_weekday_revision_minutes','maximum_weekend_revision_minutes'].map(k=>[k,plan[k]])), exams:planExams, commitments:commitments.filter((x:any)=>x.plan_id===planId).map((x:any)=>({title:x.title,commitment_type:x.commitment_type,recurrence_type:x.recurrence_type,day_of_week:x.day_of_week,specific_date:x.specific_date,start_time:x.start_time,end_time:x.end_time})), revision_topics:planTopics.map((x:any)=>({...x,display_name:topics.find((t:any)=>t.id===x.topic_id)?.name||x.custom_topic_name,to_improve_count:comments.filter((c:any)=>c.topic_id===x.topic_id&&c.status!=='resolved').length})), activities:activities.filter((x:any)=>activityByTopic.has(x.revision_topic_id)), existing_sessions:planSessions.map((x:any)=>({id:x.id,...x})), instruction: mode==='edit'?instruction:undefined }
    const schema = { type:'object', additionalProperties:false, required:[mode==='edit'?'changes':'sessions','summary','unscheduled'], properties:{ summary:{type:'string'}, unscheduled:{type:'array',items:{type:'object',additionalProperties:false,required:['revision_topic_id','activity_label','remaining_minutes','reason'],properties:{revision_topic_id:{type:'string'},activity_label:{type:'string'},remaining_minutes:{type:'number'},reason:{type:'string'}}}}, sessions:{type:'array',items:{type:'object',additionalProperties:false,required:['exam_id','revision_topic_id','subject_id','activity_label','scheduled_date','start_time','end_time','generated_reason'],properties:{exam_id:{type:'string'},revision_topic_id:{type:'string'},subject_id:{type:'string'},topic_id:{type:['string','null']},title:{type:'string'},activity_label:{type:'string'},scheduled_date:{type:'string'},start_time:{type:'string'},end_time:{type:'string'},generated_reason:{type:'string'}}}}, changes:{type:'array',items:{type:'object',additionalProperties:false,required:['action','reason'],properties:{action:{type:'string',enum:['move','create','remove','resize']},session_id:{type:'string'},exam_id:{type:'string'},revision_topic_id:{type:'string'},subject_id:{type:'string'},topic_id:{type:['string','null']},activity_label:{type:'string'},scheduled_date:{type:'string'},start_time:{type:'string'},end_time:{type:'string'},reason:{type:'string'}}}} } }
    const ai = await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${Deno.env.get('OPENAI_API_KEY') ?? ''}`,'Content-Type':'application/json'},body:JSON.stringify({model:Deno.env.get('REVISION_PLANNER_MODEL')||'gpt-5.6-terra',store:false,instructions:'Create or minimally adjust a sustainable revision timetable. Use only supplied IDs. Never alter locked or done sessions, priorities, status, or commitments. Respect dates, exams, commitments, wake/sleep, capacity; report unfittable work.',input:JSON.stringify(input),text:{format:{type:'json_schema',name:'revision_plan',strict:true,schema}}})})
    if (!ai.ok) throw new Error('AI generation failed.')
    const raw = await ai.json(), text = raw.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==='output_text')?.text
    if (!text) throw new Error('AI returned no usable plan.')
    const proposal = JSON.parse(text), knownExams=new Set(planExams.map((x:any)=>x.id)), knownTopics=new Map(planTopics.map((x:any)=>[x.id,x])), knownSubjects=new Set(subjects.map((x:any)=>x.id)), locked=new Set(planSessions.filter((x:any)=>x.locked||x.status==='done').map((x:any)=>x.id))
    const validate = (s:any) => { const topic=knownTopics.get(s.revision_topic_id); if(!knownExams.has(s.exam_id)||!topic||!knownSubjects.has(s.subject_id)||topic.subject_id!==s.subject_id||(topic.topic_id||null)!==(s.topic_id||null)||!activityByTopic.get(topic.id)?.some((a:any)=>a.activity_label===s.activity_label)) throw new Error('AI referenced an invalid planner item.'); if(s.scheduled_date<plan.start_date||s.scheduled_date>plan.end_date||s.scheduled_date>planExams.find((e:any)=>e.id===s.exam_id)?.exam_date||s.start_time>=s.end_time) throw new Error('AI proposed an invalid time.'); const weekend=[0,6].includes(day(s.scheduled_date)),wake=weekend?plan.weekend_wake_time:plan.weekday_wake_time,sleep=weekend?plan.weekend_sleep_time:plan.weekday_sleep_time; if((wake&&s.start_time<wake)||(sleep&&s.end_time>sleep))throw new Error('AI proposed time outside availability.'); const blocked=[...planSessions.filter((x:any)=>x.locked),...commitments.filter((x:any)=>x.plan_id===planId&&((x.recurrence_type==='once'&&x.specific_date===s.scheduled_date)||(x.recurrence_type==='weekly'&&Number(x.day_of_week)===day(s.scheduled_date)))]; if(blocked.some((x:any)=>overlaps(s.start_time,s.end_time,x.start_time,x.end_time)))throw new Error('AI proposed a conflict.'); }
    if(mode==='edit') { for(const change of proposal.changes||[]){if(change.action!=='create'&&(!change.session_id||locked.has(change.session_id)))throw new Error('AI attempted to change a protected session.');if(change.action==='create'||change.action==='move'||change.action==='resize')validate(change.action==='create'?change:{...planSessions.find((x:any)=>x.id===change.session_id),...change});} return reply({proposal,request_id:requestId,preview:true}) }
    for(const session of proposal.sessions||[]) validate(session)
    const generated=(proposal.sessions||[]).map((s:any)=>({owner_id:user.id,plan_id:planId,...s,status:'not_started',locked:false,source:'ai',notes:''}))
    if (body.replace_unlocked_ai_sessions===true) { const { error }=await admin.from('academic_revision_sessions').delete().eq('owner_id',user.id).eq('plan_id',planId).eq('source','ai').eq('locked',false).neq('status','done'); if(error)throw error }
    if(generated.length){const {error}=await admin.from('academic_revision_sessions').insert(generated);if(error)throw error}
    await admin.from('academic_revision_ai_requests').update({status:'applied',applied_at:new Date().toISOString()}).eq('id',requestId)
    return reply({created:generated.length,unscheduled:proposal.unscheduled||[],summary:proposal.summary||''})
  } catch (error) { if(requestId) await admin.from('academic_revision_ai_requests').update({status:'failed',error_message:'AI planner could not apply this request.'}).eq('id',requestId); console.error('[revision-planner]', error instanceof Error ? error.message : 'failed'); return reply({error:'AI generation failed. Your existing timetable was not changed.'},422) }
})
